services:
    jenkins-master-proj2:
        image: jenkins/jenkins:lts-jdk21
        container_name: jenkins-master-proj2
        ports:
            - "8090:8080"
            - "50000:50000"
        volumes:
            - jenkins_home:/var/jenkins_home
        networks:
            - cicd-net
        environment:
            - JAVA_OPTS=-Djava.net.preferIPv4Stack=true

    slave-app-proj2:
        image: yaroslavdomb/jenkins-slave:latest
        container_name: slave-app-proj2
        privileged: true
        dns:
            - 8.8.8.8
            - 8.8.4.4
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.default.disable_ipv6=1
        environment:
            - JENKINS_URL=http://jenkins-master-proj2:8080
            - JENKINS_AGENT_NAME=slave-app-proj2
            - JENKINS_SECRET=${SLAVE_APP_SECRET}
            - JAVA_OPTS=-Djava.net.preferIPv4Stack=true
        networks:
            - cicd-net

    slave-infra-proj2:
        image: yaroslavdomb/jenkins-slave:latest
        container_name: slave-infra-proj2
        privileged: true
        dns:
            - 8.8.8.8
            - 8.8.4.4
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.default.disable_ipv6=1
        environment:
            - JENKINS_URL=http://jenkins-master-proj2:8080
            - JENKINS_AGENT_NAME=slave-infra-proj2
            - JENKINS_SECRET=${SLAVE_INFRA_SECRET}
            - JAVA_OPTS=-Djava.net.preferIPv4Stack=true
        networks:
            - cicd-net

volumes:
    jenkins_home:
        external: true

networks:
    cicd-net:
        driver: bridge
